# This is a basic workflow to help you get started with Actions

name: CI-testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    # gem install coveralls-lcov
    # pip install coveralls
    # npm install -g bower
    # npm install -g grunt-cli
    # npm install -g karma-cli
    - name: Install JS dependencies
      run: |
        npm ci
        npm install bower
        ./node_modules/bower/bin/bower install

    - name: Create conda environment
      run: |
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda info -a
        conda create -q -n test-environment python=3.6.10
        conda init
        conda activate test-environment



    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
