# This is a basic workflow to help you get started with Actions

name: CI-testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: 'latest'
        activate-environment: test-environment
        python-version: 3.6.10
        auto-activate-base: false
        auto-update-conda: true
        condarc-file: test/condarc.yml

    - name: Use Node js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    # gem install coveralls-lcov
    # pip install coveralls
    # npm install -g bower
    # npm install -g grunt-cli
    # npm install -g karma-cli
    - name: Install JS dependencies
      run: |
        npm ci
        npm install bower
        ./node_modules/bower/bin/bower install

    - name: Install Narrative Application
      shell: bash -l {0}
      run: |
          bash ./scripts/install_narrative.sh
          grunt minify
          sed <src/config.json.templ >src/config.json "s/{{ .Env.CONFIG_ENV }}/dev/"
          sed -i 's/{{ if ne .Env.CONFIG_ENV "prod" }} true {{- else }} false {{- end }}/true/' src/config.json
          jupyter notebook --version

    - name: Run Narrative Test Suite
      shell: bash -l {0}
      run: make test

    - name: Setup Ruby for coverage mapping
      uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

    - name: Combine coverage results
      shell: bash -l {0}
      run: |
        gem install coveralls-lcov
        coveralls-lcov -v -n js-coverage/lcov/lcov.info > js-coverage.json
        coveralls --merge js-coverage.json

    - name: Send to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
